name: CI

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install black==24.8.0 sqlfluff==3.0.5 pytest

      - name: Create sqlfluff config (sparksql)
        run: |
          echo "[sqlfluff]" > .sqlfluff
          echo "dialect = sparksql" >> .sqlfluff

      # --- Python formatting (Black) ---
      - name: Black (check)
        shell: bash
        run: |
          PY_FILES="$(git ls-files '*.py')"
          if [ -z "$PY_FILES" ]; then
            echo "No Python files to check. Skipping Black."
          else
            black --check $PY_FILES
          fi

      # --- SQL lint (non-blocking while you build) ---
      - name: SQLFluff (lint SQL non-blocking)
        shell: bash
        run: |
          if compgen -G "databricks/sql/*.sql" > /dev/null; then
            sqlfluff lint databricks/sql || true
          else
            echo "No SQL files to lint. Skipping SQLFluff."
          fi

      # --- Tests (optional, non-blocking for now) ---
      - name: Pytest (optional)
        run: pytest || true
